# Generated by Django 4.0.3 on 2022-03-04 17:43

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
